# Generated by Django 2.2.12 on 2021-01-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='no',
            field=models.CharField(max_length=7),
        ),
    ]
